# Generated by Django 3.2.9 on 2021-11-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='estimated_time',
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_date',
            field=models.DateTimeField(),
        ),
    ]
